### PR TITLE
updated tlp-pmu and readded light-locker-consolekit

### PR DESCRIPTION
**Pull request by aadityabagga**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
who is packaging **tlp-pmu** and **light-locker-consolekit**

**Comment by aadityabagga** [comment]
@oberon2007 has packaged an older version of light-locker-consolekit which I have requested him to remove or update via PM, I could package these two (but I do not know boxit nor have boxit rights), else @udeved could do it if he wants to or yourself @philmmanjaro

**Comment by oberon2007** [comment]
I can repackage it. Removing is not an option since we need it for the OpenRC-ISOs and I would like to avoid the custom SF repo ;)

**Comment by oberon2007** [comment]
updated l-l-ck https://github.com/manjaro/packages-community/commit/3fbc8f79afb11f87d6b109eb508274f7f3762edd

**Comment by oberon2007** [comment]
So I'll do tlp-pmu aswell and I guess I should move the PKGBUILD of light-locker-consolektit from -community to -openrc... right?

**Comment by oberon2007** [comment]
Or keep the PKGBUILDS of the pkgs we have in -community there? Would be more logic maybe.

**Comment by aadityabagga** [comment]
Yup, most of the OpenRC packages that are in community have packages in this repo.

**Comment by philmmanjaro** [comment]
**openrc** packages we keep in this git-repo so we can keep track of them with ease. However, all of them will be uploaded to community.

**Comment by oberon2007** [comment]
We can simply download the packages from the SF repo, sign them locally and then boxit to community. Or would it not maybe be clearer to have a separate openrc-repo reflecting the form of the the github-repos?

**Comment by philmmanjaro** [comment]
boxit currently doesn't support any other repos as **core**, **extra** and **community** plus **multilib**. We might add that for the future.

**Comment by oberon2007** [comment]
Ok. do you want everything in community already? I can migrate the whole lot if you like... :ant

**Comment by philmmanjaro** [comment]
@oberon2007: keep the **openrc** PKGBUILDs in the **packages-openrc** git-repo. That way we know which packages need to been updated. All **openrc** PKGBUILDs currently inside of **packages-community** should be moved out of there and migrated into **packages-openrc** git-repo.

**Comment by oberon2007** [comment]
Yes. PKGBUILDs can be moved as soon as @aadityabagga 's latest commit is merged. Otherwise we have conflicts. I had already tried earlier with **light-locker-consolekit**... That PKGBUILD I have parked here locallly meanwhile.
I was talking about the actual packages. I thought that was what you meant, no?
> all of them will be uploaded to community.

If you want to have that done I can just sync the [SF-repo](https://sourceforge.net/projects/archopenrc/files/openrc-eudev/), sign the packages and boxit them.
Just let me know.
Or maybe @aadityabagga and @udeved should decide first what we need.
In any case using that Sourceforge-repo for building ISOs does not work really - you get timeouts all the time...

**Comment by aadityabagga** [comment]
Hi @oberon2007, you could commit your changes, and I could pull and rebase to avoid conflicts.

**Comment by oberon2007** [comment]
ok, good! :)

**Comment by oberon2007** [comment]
Well, sofar I only found light-locker-consolekit :) That one is moved now.

**Pull request closed without merging**
