### PR TITLE
add travis-ci bot

### PR DESCRIPTION
**Pull request by aadityabagga**
This PR adds travis-ci.org built bot, documentation for which is available here: https://docs.travis-ci.com/user/getting-started

### How its done

[.travis.yml](https://github.com/aadityabagga/packages-openrc/blob/travis-ci/.travis.yml) is the file that specifies whats going to be done, I will summarize it briefly:

* first it checks if any packages got changed from previous git commit to current commit, if no packages got changed nothing is done, if packages changed we proceed forward. _[before_script]_

* it sets up a build environment (manjaro chroot) in which packages can be built; this needs to be done because travis-ci images run ubuntu. This stage takes around 5-6 minutes on average. _[before_script]_

* after setting up the chroot and configuring it as required, it starts building packages in the chroot using buildpkg. _[script]_

* if packages got built, it currently deploys them to a test repo on [sourceforge](https://sourceforge.net/projects/mefiles/files/Manjaro/test/packages-openrc/x86_64/). _[after_success]_

* finally it gives a summary of what packages got built. _[after_script]_

Here is what it looks like: https://travis-ci.org/aadityabagga/packages-openrc/builds/243088297

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Looks great. I've two things which are not yet clear for me:

* What about security? I see the file **id_rsa_sf.enc**, which seems to be a ssh-key for SF.net. How is this file generated and how secure is it to be cracked?
* The Test-Repo simply uploads the package without signing it. In a later step we even may add a function to support **repo-add** or even **boxit** to upload to our main-repos somehow. However we should make brute-force attacks almost not possible and such.

Those two topics can also be discussed by email or in our forum.

**Comment by philmmanjaro** [comment]
`/usr/lib/manjaro-tools/util.sh: line 268: /etc/lsb-release: No such file or directory`, which is part of **manjaro-release** and issues with **locale** should be also fixed. IMO.

**Comment by aadityabagga** [comment]
@philmmanjaro: "I see the file id_rsa_sf.enc, which seems to be a ssh-key for SF.net."
Quite right :-) As per https://docs.travis-ci.com/user/encrypting-files/ they use symmetric encryption (AES-256). I encrypted the file using their travis ruby gem client on the command line:
~~~~
~/.gem/ruby/2.2.0/bin/travis encrypt-file ~/.ssh/id_rsa_sf --add
~~~~
The encryption is personal to my account, and when the pull request gets accepted the admin of the repo can enable it in travis-ci settings and encrypt their key using same command.

<hr>

We can add repo-add support by copying from and modifying https://github.com/arch-openrc/build-openrc/blob/master/build_openrc.sh#L221

Will add manjaro-release to the list of bootstrapped-packages.

**Comment by philmmanjaro** [comment]
@aadityabagga: looks all promessing so far. Is there already an example repository created by this **build-bot**? Also, I assume this bot works for basic packages and not yet to compile a proper [tool-chain](http://www.linuxfromscratch.org/lfs/view/development/chapter05/introduction.html).

**Comment by aadityabagga** [comment]
@philmmanjaro: not exactly a repository, just a collection of packages till we can integrate repo-add: https://sourceforge.net/projects/mefiles/files/Manjaro/test/packages-openrc/x86_64/

Yup, I think so. Before setting it up for deployment (especially for core manjaro-repos), I think we can use this as a CI system and test it with all kinds of packages to ensure that packages are getting built after making changes.

**Comment by aadityabagga** [comment]
Closing, https://forum.manjaro.org/t/manjaro-openrc-will-be-discontinued/28387/

**Pull request closed without merging**
