### PR TITLE
update networkmanager-consolekit and its change polkit rules

### PR DESCRIPTION
**Pull request by aadityabagga**
Hi artoo,

With this change in polkit rules, I am able to turn networking on/off from network-manager-applet (was not able to do this before). Also updated the version.

Would it be possible to build and upload it quickly?

### CODE REVIEW

**Comment by aadityabagga** [comment]
Tagging @udeved since he does not seem to be in the watch list.

**Comment by udeved** [comment]
I think NM has got a new release anyway to update.

**Comment by aadityabagga** [comment]
Thx for the quick response. :)

**Comment by udeved** [comment]
I won't get to use boxit until Sunday, I am away, and laptop doesn't have the gpg sig set up.

**Comment by aadityabagga** [comment]
Hmm, maybe I could add it to the openrc-eudev repo then for the time being...

**Comment by udeved** [comment]
Or you do boxit. :)

**Comment by philmmanjaro** [comment]
You're never alone ;) Uploading it to unstable soon.

**Comment by philmmanjaro** [comment]
@aadityabagga: please build the package or tell me how to build openrc packages. My chroot pulled systemd in, so I abort my build here ...

**Comment by aadityabagga** [comment]
Thx for the help @philmmanjaro :)

I am building it currently, will post here when done.

What I do is that I do buildpkg with a simple package like sysvinit, then manually chroot into the chroot created by buildpkg and install eudev and eudev-systemdcompat before building other packages.

**Comment by udeved** [comment]
@philmmanjaro 

Its ok to build against systemd.
It only requires libudev.
Just build the package, the configure will use ck tracking anyway, which is the important thing.

**Comment by aadityabagga** [comment]
@udeved 's logic here seems valid.

64 bit done available here, 32 bit could take some time due to updating...
http://sourceforge.net/projects/archopenrc/files/openrc-eudev/x86_64/networkmanager-consolekit-1.0.2-1-x86_64.pkg.tar.xz

**Comment by aadityabagga** [comment]
Hmm, polkit rules are causing trouble when installing...

~~~~
networkmanager-consolekit: /opt/buildiso/xfce-openrc/x86_64/xfce-image/etc/polkit-1/rules.d/01-org.freedesktop.ModemManager1.rules exists in filesystem
networkmanager-consolekit: /opt/buildiso/xfce-openrc/x86_64/xfce-image/etc/polkit-1/rules.d/01-org.freedesktop.NetworkManager.settings.modify.system.rules exists in filesystem
~~~~

@udeved do they exist in some other package as well?

**Comment by udeved** [comment]
Oh, I think we need to rebuild ck.
I haven't rebuild yet, as I was hoping for a new ck release as announced by the dev.

**Comment by aadityabagga** [comment]
ah, got it..

**Comment by udeved** [comment]
Btw, polkit-consolekit also need little change and bump.
Arch released a pk pulling from git some newer commit.

**Comment by aadityabagga** [comment]
When you are bumping packages could you give a static version to the service packages (openrc-base, openrc-destop, openrc-devel, etc)?

Dynamic version causes trouble when sometimes only package gets rebuilt but no change in version number.

**Pull request merged**
