### PR TITLE
add boinc-openrc, at-openrc

### PR DESCRIPTION
**Pull request by aadityabagga**

### CODE REVIEW

**Comment by aadityabagga** [comment]
@udeved is there some problem with the scripts?

**Comment by udeved** [comment]
I haven't had much time lately to look at it.
I just realized the pull request...

**Comment by aadityabagga** [comment]
I made some updates today as well, I could try to add them too.
https://bitbucket.org/aadityabagga/openrc-src/commits/5ed4f1cd526b2d384e6a1e9a15c7631aa77e8495

**Comment by udeved** [comment]
I updated openrc-core today to v0.14

**Comment by aadityabagga** [comment]
Yeah, I noticed..

**Comment by udeved** [comment]
Did you stick to gentoo portage tree for new packages if possible?
I would merge it then.

**Comment by aadityabagga** [comment]
Yes, they are from gentoo.
https://bitbucket.org/aadityabagga/openrc-src/src

**Pull request merged**
